version: '3.3'

networks:
  ros: # ros-master <-> ros-talker <--> backend-web

services:
  ros-master:
    build: ./ros-master
    networks:
      - ros
    restart: always
  ros-talker:
    image: ros:noetic-ros-core
    depends_on:
      - ros-master
    environment:
      ROS_MASTER_URI: &ros_master_uri "http://ros-master:11311"
      ROS_HOSTNAME: "ros-talker"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "Hello from ROS!" -r 1
    networks:
      - ros
    restart: always
  # backend-web:
  # frontend-web: