version: '3.3'

networks:
  # ros: # ros-master <--> ros-talker <--> backend
  frontend: # backend-web <--> frontend-web

services:
  ###########################
  # ROS side of the project
  ###########################
  # # ROS Master Node
  # ros-master:
  #   image: ros:noetic-ros-core
  #   command: stdbuf -o L roscore
  #   networks:
  #     - ros
  #   restart: always
  # ROS Talker Node using rosnodejs
  # ros-talker:
  #   build: ./ros-talker
  #   networks:
  #     - ros
  #   environment:
  #     ROS_HOST: ros-master
  #     ROS_PORT: 11311
  #   depends_on:
  #     - ros-master
  # ###########################
  # Web side of the project
  ###########################
  # Backend handling the connection with ROS
  # and business logic
  backend-web:
    build: ./backend-web
    networks:
      - frontend
    environment:
      ROS_HOST: "192.168.5.214"
      ROS_PORT: 9090
      API_HOST: backend-web
      API_PORT: &api_port 3001
    # depends_on:
    #   - ros-talker
  # Frontend handling the UI
  frontend-web:
    build: ./frontend-web
    networks:
      - frontend
    ports:
      - "8081:3000"
    environment:
      API_HOST: backend-web
      API_PORT: *api_port
    volumes:
      - ./frontend-web:/app
    depends_on:
      - backend-web