name: Unit Tests

on:
  push:
    branches: [*]
  pull_request:
    branches: [*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout branch
        uses: actions/checkout@v2
      - 
        name: Use Node.js
        with:
          node-version: 14.x
      - 
        name: Install dependencies
        run: yarn
      - 
        name: Run tests
        run: yarn test
